Improving the naughty bits

diff --git a/local/bin/xvideos-dl b/local/bin/xvideos-dl
--- a/local/bin/xvideos-dl
+++ b/local/bin/xvideos-dl
@@ -60,7 +60,7 @@ cleanup()
 
 highestres() {
 
-  curl -s -c .tmp/cookies "$1"|grep RESOLUTION|sed 's/^.*,NAME="\(.*\)"$/\1/'|sort -h|tail -1
+  curl -s -c ~/.tmp/cookies "$1"|grep RESOLUTION|sed 's/^.*,NAME="\(.*\)"$/\1/'|sort -h|tail -1
 
 }
 
@@ -82,7 +82,7 @@ leadingzeroes() {
   LIST=''
   for ((i=0;i<=LAST_NUM;i++)); do
     if [[ $i -lt $(($LEAD*10)) ]]; then
-      LIST=$LIST`printf ".tmp/hls-${HIGHEST_RES}0%.0s$i.ts " $LEADC`
+      LIST=$LIST`printf "/home/josh/.tmp/hls-${HIGHEST_RES}0%.0s$i.ts " $LEADC`
     else
       : # do nothing
     fi
@@ -94,8 +94,8 @@ leadingzeroes() {
     if [[ ! -f $destFile ]]; then
       # determine number, go from there
       NUM=`echo $destFile | cut -dp -f3 | cut -d\. -f1`
-      mv .tmp/hls-$HIGHEST_RES${NUM#0}.ts $destFile
-#      echo "DEBUG: I moved .tmp/hls-$HIGHEST_RES${NUM%0}.ts to $destFile"
+      mv ~/.tmp/hls-$HIGHEST_RES${NUM#0}.ts $destFile
+#      echo "DEBUG: I moved ~/.tmp/hls-$HIGHEST_RES${NUM%0}.ts to $destFile"
     fi
   done
 
@@ -124,12 +124,12 @@ echo ""
 echo "Extracting video URL from.. ==> $URL"
 
 # Should probably check for space on file system before the download is attempted
-mkdir .tmp 2>/dev/null
+mkdir ~/.tmp 2>/dev/null
 
 # Changing this declaration to account for site changes
 # For one, returned html is pre-formatted, so just do the
 # curl  and grep and be done with it
-HLS_URL=`curl -s -c .tmp/cookies "$URL"       | # download HTML using curl
+HLS_URL=`curl -s -c ~/.tmp/cookies "$URL"       | # download HTML using curl
         grep 'html5player.setVideoHLS'        | # locate lines with "html5player.setVideoHLS"
         cut -d\' -f2`                           # clean up a little
 
@@ -138,6 +138,12 @@ HLS_URL=`curl -s -c .tmp/cookies "$URL"       | # download HTML using curl
 # since they've already standardized the naming scheme for me)
 HIGHEST_RES=`highestres "$HLS_URL"`  # This needs to actually recreate the URL entirely
 #echo "DEBUG: HIGHEST_RES = $HIGHEST_RES"
+if [[ $HIGHEST_RES =~ ^[23]{1} ]]; then  # If highest resolution begins with 2 or 3 then skip this video
+  # Do cleanup early and exit
+  rm -r ~/.tmp
+  echo -e "\nNot high enough quality, fuck this video\n"
+  exit 1
+fi
 
 # Need to form the next url and then parse the response for last segment
 # second to last line
@@ -145,7 +151,7 @@ HIGHEST_RES=`highestres "$HLS_URL"`  # This needs to actually recreate the URL e
 HIGHEST_URL=`echo "${HLS_URL/hls.m3u8/hls-$HIGHEST_RES.m3u8}"` # URL Encode fixes
 #echo "DEBUG: HIGHEST_URL = $HIGHEST_URL"
 
-LAST_SEG=`curl -s -c .tmp/cookies "$HIGHEST_URL"              | # download HTML using curl
+LAST_SEG=`curl -s -c ~/.tmp/cookies "$HIGHEST_URL"              | # download HTML using curl
           tail -2|head -1`                                      # just need the last segment
 #echo "DEBUG: LAST_SEG = $LAST_SEG"
 
@@ -167,7 +173,7 @@ else
   LAST_NUM=`echo $REAL_LAST_SEG|rev|sed 's/^st\.\([0-9]\{1,\}\).*$/\1/'|rev`
 #  echo "DEBUG: LAST_NUM = $LAST_NUM"
   for ((i=0;i<=LAST_NUM;i++)); do echo ${HLS_URL/hls.m3u8/hls-$HIGHEST_RES${i}.ts}; done | xargs -n 1 -P 8 wget -q -P ~/.tmp
-  for ((i=0;i<=LAST_NUM;i++)); do mv .tmp/hls-$HIGHEST_RES${i}.ts?$PARAMETERS .tmp/hls-$HIGHEST_RES${i}.ts; done
+  for ((i=0;i<=LAST_NUM;i++)); do mv ~/.tmp/hls-$HIGHEST_RES${i}.ts?$PARAMETERS ~/.tmp/hls-$HIGHEST_RES${i}.ts; done
   leadingzeroes $LAST_NUM
 fi
 
@@ -176,7 +182,7 @@ rm -r ~/.tmp
 
 # Now re-encode to get rid of the choppy bits
 # This part sucks, replacing with ffmpeg
-ffmpeg -i ~/.a/${URL##*/}.ts -acodec copy -vcodec copy ~/.a/${URL##*/}.mp4
+ffmpeg -loglevel 24 -i ~/.a/${URL##*/}.ts -acodec copy -vcodec copy ~/.a/${URL##*/}_${HIGHEST_RES}.mp4
 
 echo ""
 echo "Done, you motherfucker. Cleaning up now."
